### ISSUE TITLE
when showing correct answer, replace spinners with numbers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#101]
Here's a screenshot from the 'Game' in Balancing Chemical Equations, at the point where the correct answer is shown. Note that the quantities are still shown using spinners. The spinners are not interactive, but they look like they are.

![screenshot_437](https://cloud.githubusercontent.com/assets/3046552/5850462/01e8a88c-a1b3-11e4-92d5-a8f7e0d95b79.png)

Reactants, Products and Leftovers has a nicer way of showing the correct answer. It replaces the spinners with numbers.  Here's a screenshot, at a similar point where the correct answer is shown. There's no question that the quantities can't be changed, and there's only one thing the user can do (press the 'Next' button).

![screenshot_438](https://cloud.githubusercontent.com/assets/3046552/5850475/31b0dcce-a1b3-11e4-9b28-f0e41d9f8919.png)

Assigning to @ycarpenterphet for comment.

**Comment by ycarpenterphet** [comment]
I agree that the spinners make it look interactive when it's not, and although this hasn't been a significant problem in interviews or in the classroom, it would still be better to make the answer look non-interactive (especially now that we have games like Area Builder, where the scenario CAN still be manipulated after two attempts, and the answer is not shown).

However, I'd rather still emphasize the part of the equation that was manipulable, as opposed to using plain numbers like in RPAL. 

What about leaving the numbers in rounded boxes, but removing the arrows (replacing spinners with boxes, basically)? Thoughts?

**Comment by pixelzoom** [comment]
> What about leaving the numbers in rounded boxes, but removing the arrows (replacing spinners with boxes, basically)?

Could do. It's a bit more work, but not a big deal.

**Comment by ycarpenterphet** [comment]
Ok, let's go ahead and do that.

I'm not sure what your workload is right now, but any thoughts on how long this might take / when a dev version would be available? That'll help me decide whether to wait for the new version before I record the teacher primer video for this sim. Thanks!

**Comment by pixelzoom** [comment]
@ycarpenterphet I have a bunch of other work that takes precedence over this. But what is your desired timeframe for recording the teacher primer video?

**Comment by ycarpenterphet** [comment]
No worries @pixelzoom. It'll be easy to do a quick edit on that one frame of the answer in the video. I'll likely be re-recording the video this week, but would have held off until next week or the week following if the dev version were coming soon.

Since you've got other sim priorities on your plate, I'll go ahead an record/edit with the published version.

**Comment by pixelzoom** [comment]
@ycarpenterphet I was able to squeeze this in today, here's a dev version:

http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.0-dev.1/balancing-chemical-equations_en.html

If this is what you had in mind and you don't see any problems, please close this issue.

**Comment by ycarpenterphet** [comment]
@pixelzoom  Thanks!

A related question before I wrap this up -- Has the look/behaviour of the spinners changed in general, so that the top or bottom halves no longer highlight when mousedover?

This is what used to happen when the mouse cursor hovers, but doesn't in the dev version (even when the spinners are active)
<img width="124" alt="screenshot 2015-07-08 13 59 49" src="https://cloud.githubusercontent.com/assets/4682895/8580774/a4aa527e-2579-11e5-9d87-2945ec6b49d7.png">

**Comment by pixelzoom** [comment]
@ycarpenterphet Behavior of NumberPicker should not have changed. I'll investigate.

**Comment by pixelzoom** [comment]
I see this same issue in other sims that use NumberPicker, e.g. graphing-lines. Tracking this issue in https://github.com/phetsims/scenery-phet/issues/168.

**Comment by pixelzoom** [comment]
Fixed NumberPicker highlighting in phetsims/scenery-phet#168

@ycarpenterphet here's a new dev version:
http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.0-dev.2/balancing-chemical-equations_en.html

**Comment by ycarpenterphet** [comment]
thanks, this looks great. I'll use this dev version when I record the final primer video (and as a bonus, it will have up to date Level Selection buttons!).
