### ISSUE TITLE
modify game flow so that "Try Again" is optional?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#104]
In https://github.com/phetsims/graphing-lines/issues/47, it was requested to change the game flow so that the "Try Again" button automatically changed to "Check" when interacting with game.  

To do something similar in BCE will require non-trivial redesign and significant implementation time.  See screenshot below. Spinners are disabled so there's nothing to interact with. And the "Try Again" button is in a dialog, along with a "Show Why" button that allows the user to explore why their answer was incorrect.  

![screenshot_566](https://cloud.githubusercontent.com/assets/3046552/9093862/d2cfbaba-3b6b-11e5-9220-5a66946b3d3d.png)

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/issues/47#issuecomment-128094709, @ariel-phet stated that this should be "an open question for the design team".  Assigning to @ariel-phet to decided who from the design team should be assigned to answer this question.

**Comment by pixelzoom** [comment]
@ariel-phet If it were my call, I'd say that this is a non-issue and close as "won't fix".  The current design was vetted in interviews, no problems have been reported, and I don't think consistency with other Games for this aspect is particularly important.

**Comment by ariel-phet** [comment]
@pixelzoom agreed, since this flow is specifically designed to remove other interaction, the issue we were seeing in other games is not present. Thanks for the screenshot and insight. Closing
