### ISSUE TITLE
display best times in the game

### ISSUE THREAD

**Issue by bryo5363** [phetsims/balancing-chemical-equations#110]
I noticed in the game mode of the simulation that after the user completes a timed run of the game, the time is no longer published under the game that was completed. Not sure if this is intentional or not

**Comment by pixelzoom** [comment]
@bryo5363, you said " the time is no longer published".  Are you saying that the behavior of this sim has changed, that it used to show the best time, but no longer does?  Or that you've seen this feature in other sims and it's missing here?

Whether to display the best time for each game level is an option in common-code (see `bestTimeVisibleProperty` in vegas.LevelSelectionButton).  This feature is off by default.  There are a few sims that turn it on (e.g. graphing-lines, reactants-products-and-leftovers), but balancing-chemical-equations is not one of them.  And looking at GitHub history, it never has enabled this feature.  So I don't believe that this is a change.

As to why this sim doesn't enable that feature when other sims do... That is (imo) a subjective decision that is applied inconsistently across sims.  Some design teams feel that showing the time puts undue pressure on students. Others (including me) feel that it provides a reason to replay the game after you've gotten a perfect score, and that if you turned on the timer, then you probably won't mind seeing your best time.

**Comment by bryo5363** [comment]
@pixelzoom I must have forgot that this sim did not have time displayed. I was also testing RP&L so that might have caused some confusion. I agree that the time should be displayed; I believe that it creates motivation to continue using the simulation.

**Comment by pixelzoom** [comment]
I'm going to reopen this and ask the design team if they want to add this feature.  It seems odd that balancing-chemical-equations doesn't show the "best time", while reactants-products-and-leftovers does. Especially since the HTML5 version of both sims had the same lead designer. Perhaps it was an oversight for balancing-chemical-equations.

@ariel-phet Since the design lead is no longer with the project, could you assign this to someone to make a decision? Or make the decision yourself?

**Comment by ariel-phet** [comment]
My call is to have this feature enabled. If you choose to have the game timed, and that option is available, it seems logical to have the best timed displayed when a timed game was played.

**Comment by pixelzoom** [comment]
Roger, I'll patch this into master and the release branch.  @bryo5363 thanks for motivating this change :)

**Comment by pixelzoom** [comment]
Feature has been added to master and 1.1 branch. This was a very easy, isolated change, and can be spot checked in the next RC.

**Comment by pixelzoom** [comment]
Related to 1.1.0-rc.1 testing, https://github.com/phetsims/tasks/issues/371.

**Comment by pixelzoom** [comment]
Work has been done, and this issue has been associated with the RC task.  Closing.
