### ISSUE TITLE
Spinners continue to update after checking answer

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balancing-chemical-equations#111]
Probably not an obvious use case, but fun to report nonetheless @pixelzoom.
In the game screens, with a multi touch device, the coefficient spinners can be held down while also checking an answer. This causes the inputted answer to change after  the sim has checked for correctness.
Easy way to reproduce some consequences of this:
1. This is easiest to perform on an equation where the correct answer for one of the coefficients is "7". In the below screenshots it's the O2 molecule that should be 7.
2. Once an equation fitting this criteria is given, make only the coefficients other than the O2 correct (O2 is just for this example). Make sure the O2 is wrong, preferably 0.
3. With one finger, hold down the spinner to start increasing the coefficient. Before the number reaches 7, use another finger to press check. Don't let go of the spinner until it's at max.
4. If check was successfully pressed before O2 hit seven, you'll be prompted with the wrong answer. However, clicking "Show Why" will show a balanced answer:

![img_0054](https://cloud.githubusercontent.com/assets/5863899/12121060/97b8e382-b390-11e5-81ad-c009303609ec.PNG)

Furthermore, if this procedure is done on the second attempt of an answer and "Show Answer" is pressed you get some points...sort of:
![img_0053](https://cloud.githubusercontent.com/assets/5863899/12121065/9a761db0-b390-11e5-9ed6-af3f00cff334.PNG)

Video:
https://drive.google.com/file/d/0B3HJopSo_QqLY1k4QXBBaFA0NkE/view?usp=sharing

**Comment by ariel-phet** [comment]
@phet-steele fun find....I doubt much can be done about this multitouch issue, but we will see what @pixelzoom says

**Comment by pixelzoom** [comment]
This is a double bug in `scenery-phet`, involving `NumberPicker` and `FireOnHoldInputListener`. 

When `NumberPicker.setArrowsVisible(false)` is called (which hides the arrow buttons), the "fire-on-hold" interaction with the arrow buttons isn't canceled.  And `FireOnHoldInputListener` (which handles the events) has nothing in its API to support canceling this interaction. 

Since it affects all sims that use either of these common-code types, this issue should be moved to scenery-phet and addressed.  

I don't think that it needs to be addressed for BCE 1.1.0-rc.1, since it's not a new problem, and rather obscure. @ariel-phet do you agree?

**Comment by pixelzoom** [comment]
Looks like BCE is the only client of `NumberPicker` that currently uses the `setArrowsVisible` call.

**Comment by ariel-phet** [comment]
@pixelzoom sounds good....lets mark this issues as "won't fix" and create an issue in scenery-phet

**Comment by pixelzoom** [comment]
`sun.PushButtonModel` has a similar fire-on-hold feature, but does not use `FireOnHoldInputListener`.  Looks like it properly handles stopping the associated timer when the button is disabled.

**Comment by pixelzoom** [comment]
Thanks @ariel-phet, will do.

**Comment by pixelzoom** [comment]
Issue moved to https://github.com/phetsims/scenery-phet/issues/212.  Will not address this for BCE 1.1.0.  Closing.

**Comment by pixelzoom** [comment]
Related to RC test https://github.com/phetsims/tasks/issues/371#issuecomment-169761336.

**Comment by pixelzoom** [comment]
Reopening this so that I can have @phet-steele verify after addressing phetsims/scenery-phet#212.

**Comment by pixelzoom** [comment]
Fixed the issue in NumberPicker, tested ion iPad and desktop, demonstrated in:
http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.2.0-dev.1/balancing-chemical-equations_en.html

@phet-steele Can you please verify this fix?

**Comment by phet-steele** [comment]
@pixelzoom works for me.

**Comment by pixelzoom** [comment]
Thanks @phet-steele.
