### ISSUE TITLE
remaining 1.1.0 redeploy items

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#112]
BCE 1.1.0 has been deployed to the PhET website.  Here are the remaining items.

**Design/Admin**

- [x] Rosetta test (Opening sim to trusted translators for beta)
- [x] Check teacher tips are up to date
- [ ] Republish primer video

**Comment by ariel-phet** [comment]
2 translations up already...

**Comment by ariel-phet** [comment]
@amyh-phet can you verify teacher tips and comment on primer status?

**Comment by amyh-phet** [comment]
@ariel-phet  Teacher tips are up to date.  Primer on website uses old music, but @arnabp has produced a new version of the video using new music and Stephanie has given the okay to upload.   I can check to see when the new version will be live on the website.

**Comment by ariel-phet** [comment]
@amyh-phet excellent, when republished please check off that item and close the issue.

**Comment by ariel-phet** [comment]
I think since the primers are dealt with by separate issues this can be closed
