### ISSUE TITLE
Game should retain most recent score

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balancing-chemical-equations#113]
The level selection screen needs to be changed to display stars for the most recent score achieved in a level. Currently the sim will always display the high score. Not a high priority issue, no need for a maintenance release. It's okay to wait until next re-deploy. See https://github.com/phetsims/balancing-act/issues/63 for the original issue.

**Comment by pixelzoom** [comment]
Deferred until phetsims/vegas#51 is resolved.

**Comment by pixelzoom** [comment]
This decision needs to be revisited, see https://github.com/phetsims/graphing-lines/issues/61#issuecomment-291296234.

**Comment by pixelzoom** [comment]
In 12/15/23 design meeting, we decided to stick with showing best score.  See notes in https://github.com/phetsims/vegas/issues/51#issuecomment-1858343945.

So closing this issues as "won't fix".
