### ISSUE TITLE
Game level section buttons are not centered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#117]
The level selection buttons in the Game screen are all shifted right.

I noticed this today while spot testing some major changes to sun buttons (https://github.com/phetsims/sun/issues/274).  Probably not related to that, but I really have no idea what's causing this. 

This is in master @1a2dab82782fb204d42664827aed92a16becf70d.

**Comment by pixelzoom** [comment]
Here's a screenshot, with `?dev` to show layoutBounds.

![screenshot_80](https://cloud.githubusercontent.com/assets/3046552/20505972/d003c566-b00d-11e6-97ee-276608edaf8d.png)

**Comment by pixelzoom** [comment]
I tracked this down.  The buttons are created and positioned at LevelSelectionNode line 53:

```js
var buttons = [];
    for ( var level = model.LEVELS_RANGE.min; level <= model.LEVELS_RANGE.max; level++ ) {
      buttons.push( createLevelSelectionButton( level, model, viewProperties.timerEnabledProperty ) );
    }
    var buttonsParent = new HBox( {
      children: buttons,
      spacing: 50,
      resize: false,
      center: layoutBounds.center
    } );
    this.addChild( buttonsParent );
```

The option `center: layoutBounds.center` should properly center the buttons, and was indeed doing so until just recently.   If I remove that option and handle the positioning after adding the node to the scenegraph, then problem fixed.  Like this:

```js
var buttonsParent = new HBox( {...} );
this.addChild( buttonsParent );
buttonsParent.center = layoutBounds.center;
```

No idea why this behavior has suddenly changed.  @jonathanolson has something changed in scenery?

**Comment by pixelzoom** [comment]
I see many recent nontrivial changes to LayoutBox, the supertype of HBox.

**Comment by pixelzoom** [comment]
I rolled back to LayoutBox 11/17/15 and the problem went away. Stepping forward 1 commit (11/4/16) cause the problem to appear.

**Comment by jonathanolson** [comment]
Pushed fix, other related issue is https://github.com/phetsims/scenery/issues/585. Can you test?

**Comment by pixelzoom** [comment]
Verified. Thanks, closing.
