### ISSUE TITLE
disable showAnswers in production versions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#118]
phetsims/joist#406 is a prerequisite to this.

In BCEQueryParameters, set `showAnswers` to false if we're running a production version, so that answers can't be revealed.

**Comment by pixelzoom** [comment]
Deferred until we have a way to identify production versions, see phetsims/joist#406.

**Comment by pixelzoom** [comment]
This has been addressed and is awaiting deployment.

**Comment by KatieWoe** [comment]
This looks good 1.2.0-rc.1
