### ISSUE TITLE
User suggestion: teeter-totter confusion

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balancing-chemical-equations#119]
> In the balancing equations sim (HTML)  I think the the  scales  / see-saws ( teeter-totters to you!)   can cause confusion.  This is because, for example on the N2 H2 NH3  version the N scale  is on the left of the reaction and the H scale  is on the right.
> 
> Everything else is equally spaced around the reaction arrow.
> 
> I think it takes students a while to figure out the separate scales are not linked to a side of the equation.  my experience with students was that they just adjusted numbers till they got a happy face, and didn't really get the idea of the scales until it was very directly gone through.
> 
> Layout might be difficult but ideally the scales would all be lined up vertically around the reaction arrow.
> 
> An alternate would be to have the scales in a separate bot not lines up with the reaction.

**Comment by pixelzoom** [comment]
> Layout might be difficult but ideally the scales would all be lined up vertically around the reaction arrow.

If we pursue this suggestion... This would involve moving everything down, shrinking the scales, and horizontally centering them about the reaction arrow. The worst-case scenario is "Combust Methane", which has 3 scales.  Here's what that might look like:

![bce-scales](https://cloud.githubusercontent.com/assets/3046552/23522072/e40e7c42-ff3e-11e6-9bea-b3a016e1c302.jpg)

**Comment by pixelzoom** [comment]
@ariel-phet please assign and prioritize.

**Comment by ariel-phet** [comment]
@oliver-phet please reply to the customer and let them know we appreciate the suggestion. The customer is generally correct in that I can see how this layout could cause a bit of confusion, but we just do not have the bandwidth to figure out a way to make it work better currently. I think I would tell the customer that we generally agree with suggestion but the change would be too expensive in terms of redesign and development for us to justify at this time.

That being said, this is one of our most popular sims (we often have teachers commenting on it when used on twitter and discussing how effective the sim is), there are multiple representations for visualizing the balance, and this is the first I have heard of a confusion.

Feel free to close this issue once the customer has been replied to.

**Comment by oliver-phet** [comment]
Reply to user sent. Closing.

**Comment by oliver-phet** [comment]
Another user just wrote in with a similar request:

> I know these are already done and you are working on new simulations, but after multiple years of using the Balancing Equations simulation, I have one idea for a tweak that would REALLY influence student understanding. 
> Right now, the balances for different elements are simply arranged over the reaction pictures.
> ![image](https://user-images.githubusercontent.com/5090275/151425123-e62f8258-2388-41d5-81de-5f332d437f07.png)
> The problem is that students then think the left balance represents the reactants and the right balance represents the products! I know, to experienced users this is not a big deal, but I imagine that many teachers (like me) use this simulation to INTRODUCE balancing, so it makes a big difference. I've ended up making a picture (see below) to show my students what it "should" look like. Of course I could simply explain what the balances represent, but that kind of defeats the purpose of using a simulation to let the students figure that out 
> ![image](https://user-images.githubusercontent.com/5090275/151425166-e08e12c3-22fc-4657-8d89-481d0587e4ca.png)
> Thanks! This just seems like such a little tweak in the coding, that maybe it might be possible to do even retrospectively?

**Comment by pixelzoom** [comment]
@oliver-phet please confirm with @ariel-phet and @arouinfar.  But I expect that @ariel-phet's response in https://github.com/phetsims/balancing-chemical-equations/issues/119#issuecomment-283748074 is still relevant.  While we realize the potential misconception, there is simply no screen real estate available to use the layout suggested by the user.

**Comment by arouinfar** [comment]
I would agree with @ariel-phet's earlier assessment. While this is now a recurring request, it's still infrequent.

If we were to spend some serious time on this simulation, we could maybe consider a query parameter to change the layout to center the scales. I just don't see it being a reasonable layout for the default configuration.
