### ISSUE TITLE
replace Unicode check marker and X with font-awesome icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#120]
See https://github.com/phetsims/unit-rates/issues/180

**Comment by pixelzoom** [comment]
Done, screenshots below.  @amanda-phet since you're reviewing this same change for graphing-lines (https://github.com/phetsims/graphing-lines) would you mind reviewing this one too?

![screenshot_309](https://cloud.githubusercontent.com/assets/3046552/23820968/bb9fda1c-05e2-11e7-8102-b3b03b140666.png)

![screenshot_310](https://cloud.githubusercontent.com/assets/3046552/23820969/bf6751c0-05e2-11e7-8f6e-205cdff0a6a7.png)

**Comment by pixelzoom** [comment]
Btw... Yes, the check mark in this sim really is 'yellow', whereas the check mark is green in graphing-lines.  Here's a screenshot of the currently published version:

![screenshot_310](https://cloud.githubusercontent.com/assets/3046552/23820977/14161634-05e3-11e7-90bf-136dd53f3468.png)

**Comment by pixelzoom** [comment]
Btw... yes, the color of the check mark in this sim really is 'yellow', I didn't change it. (It's green in graphing lines.)  Here's a screenshot of the published version:

![screenshot_311](https://cloud.githubusercontent.com/assets/3046552/23820983/40768d26-05e3-11e7-8fbf-3e22ce701c5f.png)

**Comment by amanda-phet** [comment]
>Btw... yes, the color of the check mark in this sim really is 'yellow', I didn't change it.

I was going to ask... it doesn't look right, and the original check with the drop shadow looks better in yellow. Should we change it to green?

**Comment by pixelzoom** [comment]
Trivial to change it to green, and I agree that green would look better.  But your call @amanda-phet.

**Comment by pixelzoom** [comment]
@amanda-phet Here's a screenshot showing how it balancing-chemical-equations would look with the same green used in graphing-lines,`'rgb( 0, 180, 0 )'`.

![screenshot_312](https://cloud.githubusercontent.com/assets/3046552/23835512/39b4dc30-072e-11e7-968b-09a3c1315dd8.png)

**Comment by amanda-phet** [comment]
I like the green better since there is no shadow behind the check.

**Comment by pixelzoom** [comment]
Done.  

Discussed with @amanda-phet, this does not warrant a maintenance release.  It will be picked up the next time we create a release branch. 

Closing.
