### ISSUE TITLE
Way to include more about Stoichiometry? 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balancing-chemical-equations#122]
When meeting with St. Vrain teachers about the iPad app, they mentioned that there is no good resource for helping teach students stoichiometry.

This would likely be the realm of another sim, but thought I would put the comment here, since it would likely be an extension/related to this sim.

Basically, they wanted a way to better enforce the "mole map" as shown below. They seemed to think if we made a sim in this realm it would be exceedingly popular.

![26186c154c2319bc82195d11c6cea15d](https://cloud.githubusercontent.com/assets/4051174/25459831/75afd766-2a9d-11e7-8f28-293c34fc00fb.png)

**Comment by ariel-phet** [comment]
@amyh-phet no serious action needed here, but if you get a chance, could you give your thoughts? maybe a quick brain dump of what you think might be useful in such a sim? Is this a topic your students struggle with?

**Comment by pixelzoom** [comment]
Doesn't @oliver-phet maintain a "suggested sims" notebook in Unfuddle? Should this issue be there?

**Comment by amyh-phet** [comment]
@ariel-phet   Stoichiometry is a notoriously difficult concept for students to master.  I think many students lack conceptual understanding of what a mole is, have trouble conceiving of a quantity as large as a mole, and end up surviving the unit by memorizing an algorithm to solve problems.   The map you included above is commonly used to help students map their way through a stoich problem.  I've also seen versions that include concentration (molarity) in addition to mass, volume, and particles.

When I teach stoich, I typically start with using a balanced chemical equation to compare moles of chemicals involved in the reaction.  Students need to understand the coefficients in the equation can either represent particles or moles of particles.  Then students investigate why the coefficients don't represent gram amounts of the substances involved in a chemical reaction.  This leads to how to convert from grams to moles of a substance.  Finally, we work multi-step problems where students must start with grams of substance A and calculate grams of substance B.  Eventually we then work to problems that involve molarity and liters.  While some teachers also include particle numbers, I tend not to teach this particular conversion as students have a hard time conceptually with the large number of particles involved and we never would measure out 6.023 x 1023 particles in a laboratory setting.

Possible learning goals:
Use a balanced chemical equation to predict the amount of reactants needed or products formed in a chemical reaction.   (Amount could refer to moles, grams, L, etc).
Predict how changing the amount of reactants available impacts the amount of products formed in a chemical reaction.
Explain why the coefficients in a balanced chemical equation do not represent the mass of the substances involved in the reaction.
Apply the law of conservation of mass to show that the total mass of reactants equals the total mass of products in a chemical reaction.


Challenges:  
Representation of substances - can’t do particulate level diagram to show 1 mole of particles.  Hard to show particulate level diagrams when dealing with grams or moles of a substance.
If more than 1 reactant or product exists, how would they be represented?  Easy to show separate reactants, but makes less sense to show products in separate containers.
Setting up a system where students could change amounts of reactants or products but wouldn’t encounter issues with limiting reactant type problems 

Possible designs:
Show balanced equation.  Have beakers containing substances below equation.  Have ability to change what is represented in beakers (grams, moles, L of gas, # of particles). Students could change amounts of a reactant, figure out how much of a second reactant is needed or determine how much of a product is made.

**Comment by pixelzoom** [comment]
@ariel-phet Re "new sim" issues like this... Rather than creating an issue like this in a sim that is possibly related, should we create a new repository for collection "new sim" idea?

**Comment by oliver-phet** [comment]
I'll add this to our suggestion spreadsheet.

**Comment by oliver-phet** [comment]
Added. Closing.
