### ISSUE TITLE
User question: startup with no atoms

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balancing-chemical-equations#123]
>  I wanted to ask about this simulation and make a suggestion. Currently, when you start the Game for Balancing Chemical Equations, all of the examples you can balance start off with no atoms/compounds on the screen. I was wondering if it could be changed to make it so that the examples start off with one of each component of the equation already on the screen.
>  
> There are a few reasons I am asking for this.
>  
> 1. You can’t balance an equation with a 0 coefficient, so it shouldn’t even be an option.
> 2. Making students/users increase to 1 for all components of the equation is tedious and unnecessary.
> 3. Students/users may be confused as to why 0 is not an option for some equations where multiple elements appear in other parts/compounds.
> 4. It is more intuitive to start with one of each so students/users can see and study the imbalance right off the back.

**Comment by pixelzoom** [comment]
The designers of this sim are no longer with PhET.  Assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
Although I see where the user is coming from, I think such a change would have many potential downsides:

1. Currently the interaction on the explore and game screens is consistent (default zero)
2. In the game the zero coefficients to begin does make a "true" statement, it might be confusing to have a false/ not balancing situation to begin with
3. We did not see any known issue in interviews with this game flow
4. The user is naturally encouraged to make a change, and when they do they "check" button becomes active (that flow would be less clear if atoms were already set 1 as default). For students still grappling with the meaning of coefficients and subscripts I think this feedback step is important.

It seems the risks and potential confusions are not worth a change to a very popular and well received simulation.

@oliver-phet please thank user for the suggestion, but let them know we do not plan to change the simulation. Feel free to summarize some of my reasons.

**Comment by oliver-phet** [comment]
Email to user sent. Closing.

**Comment by oliver-phet** [comment]
Just documenting another user wrote in suggesting starting the sim with 1 for all coefficients. 

> Is it possible for the sims to start with ALL coefficients at "1" instead of at "0".  The 0s cause some confusion for my students.

I wrote back with the same response, will update this issue with any more developments.

**Comment by oliver-phet** [comment]
Documenting another user's feedback:

> I Love the balancing chemical equations Sim, I use it to teach 14-16 year olds with great success. 
> 
> However,  I think defaulting each species to ZERO at the start can lead to misconception that some reactants or products are not involved in the reaction. (See Screen shot 1 below)
> 
> Surely all species should start at "1" as the default, as this is the way a written chemical equation appears on an exam paper. (admittedly, without the explicit "1" but it is implied). (See screen shot 2 below)

I wrote back with the same response as before.
