### ISSUE TITLE
Add keyboard navigation

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balancing-chemical-equations#124]
We would like to add keyboard navigation to this sim. @zepumph would you mind working on this after 
https://github.com/phetsims/molarity/issues/37? Like https://github.com/phetsims/molarity/issues/37, this sim will require ComboBox to be instrumented.

**Comment by pixelzoom** [comment]
This sim has non-trivial issues that will impede adding keyboard navigation. See for example https://github.com/phetsims/balancing-chemical-equations/issues/125.  I recommend choosing a different sim.

**Comment by jessegreenberg** [comment]
@pixelzoom are there issues other than #125 that would make this sim difficult for keyboard navigation? That issue would take a significant effort, but the custom accordion boxes in the sim could be made accessible in less than an hour. Drawback would be long term maintenance costs as accordion boxes in this sim and sun deviate.  But I don't know if #125 will ever be worthwhile.

**Comment by jessegreenberg** [comment]
In #125, we decided that we should wait to work on a11y in this sim until we can devote time to that issue. The a11y team will reconvene and decide on another sim to tackle (we will also check in with the responsible dev first!). Closing this issue.

**Comment by pixelzoom** [comment]
@jessegreenberg asked:
> @pixelzoom are there issues other than #125 that would make this sim difficult for keyboard navigation?

I looked through the implementation, and I don't see any other cases where common UI components  should be used. 

In general, if you want to get a feel for what common UI components need to be instrumented for sim, do a string search for "SUN" and "SCENERY_PHET" to fix the `require` statements.  Throw out the `PhetFont` statements and you will have a decent list of common UI components used by the sim.

**Comment by jessegreenberg** [comment]
Nice, Ill check that way in the future, thanks.
