### ISSUE TITLE
publish 1.2.0 with ePub/LoL support

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/balancing-chemical-equations#130]
A client has requested the ePub compatible files for this simulations. Deadline for delivery is in March, but perhaps we can fit it in soonish if there are no real barriers to republishing from master and Chris has a bit of time to review. 

This would have the benefit of also capturing Legends of Learning support. Let's touch base on this at status tomorrow, and look at current QA load to see if now is a good time or not. Should do this when QA load is light.

**Comment by kathy-phet** [comment]
@arouinfar - Including you because would be a lol sim delivery too.

**Comment by pixelzoom** [comment]
This sim is in good shape - there are no outstanding issues that need to be addressed.  It could be republished at any time.

**Comment by pixelzoom** [comment]
Assigned to @ariel-phet to schedule this.

**Comment by pixelzoom** [comment]
QA is occupied with other higher priority tasks, so BCE RC testing is on hold.  Depending on how long it takes to get this back on the schedule, we might consider starting over with a fresh set of current master shas.   Unassigning until then...

**Comment by pixelzoom** [comment]
1.2.0-rc.2 is covered in https://github.com/phetsims/QA/issues/255.

**Comment by arouinfar** [comment]
@pixelzoom I had the LoL icons/metadata ready to go in #131, so I've delivered the latest BCE to our contact at LoL. Closing.
