### ISSUE TITLE
update credits for 1.2.0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#132]
Per @ariel-phet:

- [x] Add @arouinfar to Team credits, since no significant design changes have been made.
- [x] Ask @KatieWoe who to add to QA credits.

**Comment by pixelzoom** [comment]
Self unassigning, since BCE RC testing has been deferred indefinitely.

**Comment by KatieWoe** [comment]
Laura Rae, Kelly Wurtz, Jacob Romero, Liam Mulhall, and Kathryn Woessner
@lmulhall-phet @kellywurtz @rea-laura @JRomero0613 please confirm

**Comment by pixelzoom** [comment]
I've merged the new QA names into the existing list, in alphabetical order.

@arouinfar @KatieWoe here are how the credits look in master.  OK?

<img width="686" alt="screenshot_969" src="https://user-images.githubusercontent.com/3046552/51196090-9cc2d800-18ab-11e9-821f-a5c4b1de917b.png">

**Comment by arouinfar** [comment]
Looks good to me @pixelzoom. I'll leave it to @KatieWoe to confirm the QA credits.

**Comment by KatieWoe** [comment]
@pixelzoom Looks good to me

**Comment by pixelzoom** [comment]
Great, closing.
