### ISSUE TITLE
Boxes can be collapsed behind dialog

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-chemical-equations#135]
Test device:
Chromebook and Dell Laptop
Operating System:
ChromeOS and Win 10
Browser:
Chrome
Problem description:
For https://github.com/phetsims/QA/issues/237
The boxes that show the molecules in the game can be selected by clicking on the victory or loss dialog.
Steps to reproduce:
1. Use showPointerAreas to make reproduction easier
2. Go to the game screen and select a level
3. Answer the question either correctly or not
4. When the dialog comes up, click the upper left corner of it and watch the box behind it colapse

Screenshots:
![points](https://user-images.githubusercontent.com/41024075/49835584-e2e0c500-fd5c-11e8-99e6-6824b763c607.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Balancing Chemical Equations‬
URL: https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.0-rc.1/phet/balancing-chemical-equations_en_phet.html?showPointerAreas
Version: 1.2.0-rc.1 2018-12-10 21:21:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"73e761ec","branch":"HEAD"},"balancing-chemical-equations":{"sha":"9e0cd1eb","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"d1c4844e","branch":"HEAD"},"dot":{"sha":"266d3b7a","branch":"HEAD"},"joist":{"sha":"5a013a46","branch":"HEAD"},"kite":{"sha":"f3e96e5b","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"422275fd","branch":"HEAD"},"phet-io":{"sha":"a267fdb1","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"HEAD"},"phet-io-wrappers":{"sha":"29569397","branch":"HEAD"},"phetcommon":{"sha":"869b2561","branch":"HEAD"},"query-string-machine":{"sha":"e4f9e8e8","branch":"HEAD"},"scenery":{"sha":"80afaf2f","branch":"HEAD"},"scenery-phet":{"sha":"3bcbf357","branch":"HEAD"},"sherpa":{"sha":"2134a0d1","branch":"HEAD"},"sun":{"sha":"d8dfa60b","branch":"HEAD"},"tambo":{"sha":"ee53ff03","branch":"HEAD"},"tandem":{"sha":"c7a56e2e","branch":"HEAD"},"vegas":{"sha":"9b35cba0","branch":"HEAD"},"vibe":{"sha":"474ae764","branch":"HEAD"}}

</details>

**Comment by pixelzoom** [comment]
BCE does not use JOIST/Dialog for its "dialogs", it predates the existence of Dialog.  Two ways to resolve this:

(1) Use Dialog.  This probably has longterm benefits for a11y and PhET-iO.  This may take a couple of hours, and requires designer approval since the everything behind the Dialog will dim, and that's a UX change.
 
(2) Set the background of BCE's "dialogs" to `pickable: false`.   This is trivial.

@arouinfar What is your feeling on the UX change described in (1)?

**Comment by pixelzoom** [comment]
I looked at a couple of ways to work around this, and none of them are particularly good.  This is something that is unlikely to happen.  And if it does happen, there's no harm done.   So my recommendation is that we do not address this for the 1.2 release, and handle it properly (see #137) in a future release. 

@arouinfar does that sound reasonable to you?

**Comment by arouinfar** [comment]
Nice find @KatieWoe! 

While this is a somewhat strange interaction, I don't think it's particularly harmful, so I don't think it would need to be addressed for 1.2 @pixelzoom.

I had some thoughts about using the dialog, so I commented over in #137. 

I don't think there's anything else left for this issue, so closing.
