### ISSUE TITLE
use Dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#137]
This sim currently rolls its own dialogs - see `GameFeedbackDialog`, which is a Panel.   Similar to the switch to AccordionBox in #125, there will be benefits for PhET-iO and a11y if we switch to using Dialog.  We would also avoid quirks like #135.

**Comment by arouinfar** [comment]
Here's a rough mockup of a dimmed background. It doesn't looks as bad as I had initially anticipated, so perhaps concern (1) is not really anything we need to be worried about.
![image](https://user-images.githubusercontent.com/8419308/49907344-0ece7a00-fe33-11e8-9dca-a90caacad4fc.png)

I did think of another concern though...

(3) I assume the dialog will not change size depending on the Show/Hide state, which means it will need to be large enough to accommodate the scales. If that's the case, then the dialog will occlude the accordion boxes, so students will not be able to see their solution.

**Comment by pixelzoom** [comment]
Dialogs can dynamically resize to their contents, so that shouldn't be a problem,.

The more immediate question is whether you think we can defer this issue to a future release, or whether it needs to be addressed in this release.

**Comment by pixelzoom** [comment]
Dialogs can dynamically resize to their contents, or content can be scaled to keep the Dialog size fixed. So that shouldn't be a problem,.

The more immediate question is whether you think we can defer this issue to a future release, or whether it needs to be addressed in this release.

**Comment by arouinfar** [comment]
@pixelzoom seems reasonable to defer, but I'll let @ariel-phet make that call.

**Comment by pixelzoom** [comment]
Ah, I see you already made that comment in #135.   I lost track of which issue we were commenting in.

**Comment by pixelzoom** [comment]
@emily-phet I don't recall if this was one of the chemistry sims that was on the short list for a11y instrumentation.   If it is, then recommended to raise the priority of this issue, since it will be advantageous to have real Dialogs.

**Comment by emily-phet** [comment]
@pixelzoom Thanks for the heads up - we'll be finalizing our plans for the next quarter (Jul, Aug, Sep) next week. That will include deciding a next sim for @Matthew-phet to begin descriptions. I'll run our thoughts on a next sim by you before final decisions, and update this issue if it is selected.

**Comment by emily-phet** [comment]
Just following up - 
After consideration, we decided to focus on description for Molecules and Light as the new sim for this quarter (July - Sept) which will likely flow into next quarter (Oct-Dec). I don't think you're the responsible dev for that sim, but happy to discuss anything related to that one. 

I'll reach out regarding BCE and/or RPAL if when we start considering a new sim after the current batch gets progressed (likely this will come up early December as we plan for 2020!).

**Comment by pixelzoom** [comment]
I had a couple minutes today to take a look at this. I discovered that it's going to be nontrivial to switch to using `Dialog` for `GameFeedbackDialog`, so I bailed.  Specifically:

* The dialog has 1 or 2 push buttons, depending on game state.  You can't currently hide the close 'X'. You need to specify which of the button actions should be performed when using there close 'X', and override the close button listener with option `closeButtonListener`. 

* Since the dialog would be model, there would also be no reason to hide the spinners on the equation values, which is currently done.

It might be better to simply rename `GameFeedbackDialog` to something like `GameFeedbackPanel` and leave it otherwise unchanged.

**Comment by pixelzoom** [comment]
> It might be better to simply rename `GameFeedbackDialog` to something like `GameFeedbackPanel` and leave it otherwise unchanged.

I'm going to do this, note in the documentation why it's not a Dialog, and reference this issue.

**Comment by pixelzoom** [comment]
Done, closing.
