### ISSUE TITLE
Smile covers tools when strings are doubled

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-chemical-equations#138]
For https://github.com/phetsims/QA/issues/237.  Found on Win 8.1 chrome.
When stringTest=double, the smile face that appears then an equation is balanced on the introduction screen can partially cover up the "Tools" string.  This appears more obvious when stringTest=long.
![balancing chemical equations_balancing chemical equations screenshot](https://user-images.githubusercontent.com/41024075/51059210-a8ab5300-15a8-11e9-899a-e5ebe5b6c2f3.png)

**Comment by arouinfar** [comment]
Good find @KatieWoe. Looks like a `maxWidth` problem to me @pixelzoom.

**Comment by pixelzoom** [comment]
And with `stringTest=long`, see below.  `maxWidth` will need to be considerably smaller for "None" and "Tools".

<img width="900" alt="screenshot_960" src="https://user-images.githubusercontent.com/3046552/51059992-4acc3a80-15ab-11e9-97d1-206a91a3b650.png">

**Comment by pixelzoom** [comment]
To verify this in 1.2.0-rc.2, verify the behavior shown in https://github.com/phetsims/balancing-chemical-equations/issues/138#issuecomment-453660606.

**Comment by KatieWoe** [comment]
Looks good to me 1.2.0-rc.2
