### ISSUE TITLE
Add ion-electron method on game mode?

### ISSUE THREAD

**Issue by emanuelbegnis** [phetsims/balancing-chemical-equations#140]
Hi, I am a chemistry teacher from Argentina, and sometimes we use the phet simulations and games with the students. Currently the game only has the trial method, but would be nice that ion-electron method to be present too, because some equations can't be resolved on trial method only.

**Comment by pixelzoom** [comment]
@emanuelbegnis thanks for your input.

@arouinfar can you please evaluate this request?

**Comment by arouinfar** [comment]
Thank you for your suggestion @emanuelbegnis.

@pixelzoom looking into the ion-electron method (also called [half-reaction method](https://en.wikipedia.org/wiki/Half-reaction#Half-reaction_balancing_method)), it appears to be beyond the scope of this particular sim. I think it would require pretty significant design changes, so I don't think it's something we can accommodate at this time. 

@oliver-phet can you add this the spreadsheet for user requests?

**Comment by pixelzoom** [comment]
@oliver-phet when you have added this to the spreadsheet, please close this issue.
