### ISSUE TITLE
does Equation needs a dispose method?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#142]
Game creates 5 of these when level selection button is pressed.

**Comment by pixelzoom** [comment]
Equation does not currently need `dispose`.  It links to Properties of its reactants and products:

```js
    this.reactants.forEach( reactant => reactant.userCoefficientProperty.lazyLink( observer ) );
    this.products.forEach( product => product.userCoefficientProperty.lazyLink( observer ) );
```

... but Equation is an abstract base class, and the reactants and products are own owned by the subclasses.  So there is no need to call dispose for any instance of Equation.

**Comment by samreid** [comment]
I detected a TODO for this issue as part of https://github.com/phetsims/chipper/issues/946 and decided to remove the TODO.
