### ISSUE TITLE
Handle overridden Node.setEnabled method

### ISSUE THREAD

**Issue by zepumph** [phetsims/balancing-chemical-equations#145]
Since setEnabled and isEnabled were added to Node in phetsims/scenery#1100, there are places where setEnabled is now overridden where before it was a standalone method. This could be confusing. I think it is likely best to rename the local method, or handle each case individually.

Effected usages:
* BCE/EquatioNode.js
* BCE/TermNode.js

**Comment by pixelzoom** [comment]
Self assigning, since I'm the responsible developer for this sim.

**Comment by pixelzoom** [comment]
EquationNode `setEnabled` is used in the Game screen (GamePlayNode.js).

TermNode `setEnabled` is called exclusively by EquationNode `setEnabled`.

**Comment by pixelzoom** [comment]
Addressed in the above commit.  Name changes are as follows:

EquatioNode setEnabled -> setCoefficientsEditable
TermNode.setEnabled -> setCoefficientEditable

@zepumph please review.

**Comment by zepumph** [comment]
Looks great to me. Thanks!
