### ISSUE TITLE
UI sound

### ISSUE THREAD

**Issue by markgammon** [phetsims/balancing-chemical-equations#148]
As part of the work done for https://github.com/phetsims/vegas/issues/77, UI sounds got turned on for this simulation.  Before the sim is published again from master, we should decide whether to turn the UI sounds off, leave them on and design and implement sounds for the rest of the interactions, or publish with a partial sound design.

If the decision is to turn them off, this can be accomplished by adding the following line to the end of the sim's `-main.js` file:

```js
  soundManager.setOutputLevelForCategory( 'user-interface', 0 );
```

**Comment by pixelzoom** [comment]
I reviewed the state of sound for this sim, and it looks complete.  There are no custom UI sounds needed, and all common-code components have reasonable default sounds.   So this issue is ready for review the next time this sim is to be published.

**Comment by Nancy-Salpepi** [comment]
UI sounds are working nicely 👂🏻👍🏻.
Closing!
