### ISSUE TITLE
Consider converting to default layoutBounds before PhET-iO publication

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#150]
Related to https://github.com/phetsims/joist/issues/542 ... This sim uses non-standard layoutBounds, because it was a port from Java.

In BCEConstants:

```js
  SCREEN_VIEW_OPTIONS: { layoutBounds: new Bounds2( 0, 0, 768, 504 ) },
```

Someday it should be converted to standard (default) layoutBounds, as specified in ScreenView.ts:

```typescript
const DEFAULT_LAYOUT_BOUNDS = new Bounds2( 0, 0, 1024, 618 );
```

**Comment by pixelzoom** [comment]
Another thing to consider if we ever did this...  Changing the layoutBounds will require changing the position of everything on the screen. For anything that has a postionProperty, it's value will need to change.  That will create serious problems for PhET-iO clients who have set custom values of positionProperty, and it's unlikely to be something that can be addressed by migration rules.

**Comment by pixelzoom** [comment]
Per https://github.com/phetsims/phet-io/issues/1939... We should not change `layoutBounds` for published PhET-iO sims because doing so may disrupt client customizations. So we will evaluate whether to change `layoutBounds` before publishing a PhET-iO version.

**Comment by marlitas** [comment]
Closing per dev meeting request 12/7/23.
