### ISSUE TITLE
Add gameLevels query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#152]
See GLQueryParameters for an example:

```ts
  // The levels to show in the Line Game screen.
  gameLevels: getGameLevelsSchema( LineGameConstants.NUMBER_OF_GAME_LEVELS ),
```

**Comment by pixelzoom** [comment]
Done. Ready for review when this sim is going to be published again.

**Comment by pixelzoom** [comment]
Ready for review in https://github.com/phetsims/qa/issues/1167.

**Comment by Nancy-Salpepi** [comment]
?gameLevels has been added and is working correctly. 
Closing.
