### ISSUE TITLE
Should 'X' and 'Y' be translatable?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#157]
Here's the screen icon for the Intro screen:

<img width="384" alt="screenshot_3444" src="https://github.com/user-attachments/assets/bd85d1e0-80b1-4944-9ef3-f34a7699f409">

The 'X' and 'Y' are not translatable. They are placeholders for atom/molecule symbols, which are also not translatable.  Should 'X' and 'Y' be translatable?  I think not. 

Relevant code in IntroScreen.ts:

```ts
  const xPlusYText = new Text( 'X + Y', textOptions );
  const xyText = new Text( 'XY', textOptions );
```

**Comment by arouinfar** [comment]
Thanks for asking @pixelzoom. I don't think the variable/placeholder X/Y should be translatable. It seems that translators agree, because there's never been a request otherwise. BCE is one of our oldest and most translated sims. Closing.
