### ISSUE TITLE
Use typical layout for AccordionBox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#158]
This sim uses a non-standard layout for AccordionBox titles and expandCollapseButton.  

The expandCollapseButton is on the right:

<img width="896" alt="screenshot_3446" src="https://github.com/user-attachments/assets/589b5526-1dd8-41b6-bfdd-8daf77d03565">

The title is centered:

<img width="894" alt="screenshot_3447" src="https://github.com/user-attachments/assets/a3774bee-3b29-4b2c-9bc7-0ef6f653dece">

And with `?stringTest=dynamic` there is an obvious problem with keeping the title centered -- which would need to be be resolved in common code:

<img width="893" alt="screenshot_3448" src="https://github.com/user-attachments/assets/b203ccd4-4e18-4602-9f33-719cdcaec312">

@arouinfar Would it be OK to change to the more typical layout, with the expandCollapseButton on the left, and the title left-justified next to the button?

**Comment by pixelzoom** [comment]
Looking at AccordionBox... it is not doing dynamic layout of the title.  So (sigh) perhaps we should make no changes to this sim and fix AccordionBox.

Relevant code in AccordionBox.ts starts at line 716:

```ts
    // title horizontal layout
...
    // button & title vertical layout
...
```

**Comment by arouinfar** [comment]
@pixelzoom I still think it's worthwhile to switch over to a more traditional AccordionBox. I often forget that these boxes are collapsible, as the ExpandCollapseButton is easy to overlook in its current position.

**Comment by pixelzoom** [comment]
It turns out that I have a slight preference for centering the accordion box titles so I did not change that.

What I did change:
* Move expandCollapseButton to the left (default) position.
* Keep title centered when the string changes.
* Clicking on the title expands the accordion box.

@arouinfar please review, close if OK.  And if you really prefer the title to be left aligned, that's easy to do.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The changes look good on main. I agree, the centered ttiles feel better here. Closing.
