### ISSUE TITLE
Update credits for 1.3 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#159]
The current credits are:

<img width="615" alt="screenshot_3457" src="https://github.com/user-attachments/assets/8de2d793-c9d0-476a-941d-8b946eb2aedb">

**Comment by pixelzoom** [comment]
Please specify update to QA credits for https://github.com/phetsims/qa/issues/1167.

**Comment by pixelzoom** [comment]
Looks like the checklist was not completed in https://github.com/phetsims/qa/issues/1167, and QA credits did not get noted here. Unfortunately I did not notice until I had created the 1.3 branch.  So I'm going to add the testers that seem to have particpated in https://github.com/phetsims/qa/issues/1167 (@KatieWoe, @Nancy-Salpepi, @Matthew-Moore240) and patch the 1.3 branch before publishing 1.3.0-rc.1.

**Comment by pixelzoom** [comment]
Please verify that I added the correct QA credits for https://github.com/phetsims/qa/issues/1167 -- see https://github.com/phetsims/balancing-chemical-equations/issues/159#issuecomment-2472049632.

Please specify updates to QA credits for https://github.com/phetsims/qa/issues/1171.

**Comment by Nancy-Salpepi** [comment]
>Please verify that I added the correct QA credits for https://github.com/phetsims/qa/issues/1167 -- see https://github.com/phetsims/balancing-chemical-equations/issues/159#issuecomment-2472049632.

Yes you did. Thanks 😊

>Please specify updates to QA credits for https://github.com/phetsims/qa/issues/1171.

Please add Ashton Morris

**Comment by pixelzoom** [comment]
QA credits have been updated, and we're done here. 

We've completed the QA process, but PhET build tools require deploying an RC (1.3.0-rc.3) before doing a production deploy.  That RC will not be submitted to QA.
