### ISSUE TITLE
Show Why button off-center when switching locale

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balancing-chemical-equations#164]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Safari 18.0.1

**Problem description**
For https://github.com/phetsims/qa/issues/1167 on the Game Screen: 
After an incorrect answer, changing locales while the Not Balanced dialog is up results in the Show Why button becoming off-center. This is most easily seen with ?stringTest=dynamic. 

**Steps to reproduce**
1. Add ?stringTest=dynamic to the end of the url
2. Choose any level on the Game screen
3. Change the coefficient for any reactant/product 
4. Press Check
5. Continually press the down button

OR
1. Choose any level on the Game screen
2. Change the coefficient for any reactant/product 
3. Press Check
4. In Preferences, change the locale (eg. Italian)

**Visuals**
<img width="564" alt="Screenshot 2024-11-12 at 8 17 19 AM" src="https://github.com/user-attachments/assets/47d891bb-b036-4c50-8063-47e75dc63122">
<img width="441" alt="Screenshot 2024-11-12 at 8 32 40 AM" src="https://github.com/user-attachments/assets/8736964d-a02e-481e-b12b-6980e8bbba15">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi I meant to do that, to give you something to find. (Not :)

Reproduced in main.  Weird that this happend when changing locale, but not with `stringTest=dynamic`.

**Comment by pixelzoom** [comment]
Also weird that this happens with some locales (e.g. Italiano) but not others (e.g. Español):

<img width="418" alt="screenshot_3595" src="https://github.com/user-attachments/assets/92b2e978-8626-4b2d-afca-8baaf8ad7a89">

**Comment by pixelzoom** [comment]
As @Nancy-Salpepi noted, this also happens _sometimes_ with `stringTest=dynamic` and up/down arrow buttons.  But never with left/right arrow buttons.

**Comment by pixelzoom** [comment]
The problem was that the 'Show Why' and 'Hide Why' buttons (only one of which is visible at a time) were wrapped in a Node, not in something that handles dynamic layout.  So even though one of these buttons was invisibile, it was still involved in the layout. Wrapping them in an HBox resolves the problem.

@Nancy-Salpepi please review in main, close if OK.  Please take a close look at all aspects of this pseudo-dialog, because I also did some much-needed cleanup on this code.

**Comment by Nancy-Salpepi** [comment]
All versions of the dialog look good:
- Balanced
- Balanced but not simplified
- Not balanced w/Show Why button
- Not balanced w/Hide Why button
 
Tested with ?stringTest=dynamic/long/double and cycling through locales. 
Closing!
