### ISSUE TITLE
Update screenshots for the 1.3 release

### ISSUE THREAD

**Issue by arouinfar** [phetsims/balancing-chemical-equations#165]
Related to https://github.com/phetsims/balancing-chemical-equations/issues/154

There are a few minor visual changes since the last release, so it would be nice to update the screenshots.

@Nancy-Salpepi can you take care of this?  Feel free to change the depicted scenarios or add an extra alt screenshot, if you'd like.

Please also update the screen-specific screenshots.

**Comment by Nancy-Salpepi** [comment]
Screenshots are ready for review! I didn't make any changes to the existing scenarios. I added an alt3, but feel free not to use it. 

https://o365coloradoedu-my.sharepoint.com/:f:/g/personal/nasa9473_colorado_edu/EtEAnuOCPIpGmKLIA16LSU0BIy8q2V7LLEm3-8bi2S85-w?e=mcCD2c

**Comment by arouinfar** [comment]
Looks great, thanks @Nancy-Salpepi! Committed to main above, closing.
