### ISSUE TITLE
Nav Bar Icons misaligned with dynamic long strings

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/balancing-chemical-equations#167]
**Test device**
Win 11 Desktop

**Operating System**
Win 11 23H2

**Browser**
Firefox 132.0.1

**Problem description**
For https://github.com/phetsims/qa/issues/1171 Nav Bar Icons are misaligned, it seems like this issue could be connected to this issue https://github.com/phetsims/joist/issues/982

**Steps to reproduce**
1. Use the "?stringTest=dynamic" query parameter and cycle through some of the longer options

**Visuals**
![image](https://github.com/user-attachments/assets/fcfbbc93-0d6a-4737-a783-8fec114a9136)

<details>

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Balancing Chemical Equations‬
URL: https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.3.0-rc.1/phet/balancing-chemical-equations_all_phet.html
Version: 1.3.0-rc.1 2024-11-13 01:09:08 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
Language: en-US
Window: 2048x1019
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0), or similar)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
Thanks for reporting @Matthew-Moore240.   This is a common-code problem, which PhET has decided to defer rather than address: see https://github.com/phetsims/joist/issues/982#issuecomment-2477263766.  So closing this as "won't fix".
