### ISSUE TITLE
substitute or add equations to the game

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#59]
@ycarpenterphet wrote in email:
> I may have one new equation to add or substitute into the Level 3 equation pool. CM, can you let me know how difficult this would be to implement?

This will be relatively easy *if* there are no new atoms or molecule types involved. If the equation involves a molecule that’s not supported by nitroglycerin (the chemistry common-code library) then that will be a bit of work. 

Supported atoms (elements) are here:
https://github.com/phetsims/nitroglycerin/blob/master/js/Element.js

Supported molecules are here:
https://github.com/phetsims/nitroglycerin/tree/master/js/nodes

**Comment by pixelzoom** [comment]
Unassigning. We'll triage this the next time the sim is published.

**Comment by pixelzoom** [comment]
@samreid This was an idea that @ycarpenterphet had. Her most recent status on the issue was (https://github.com/phetsims/balancing-chemical-equations/issues/59#issuecomment-49087820):
> I've done some digging into possible reactions, but haven't found any that are reasonable at this time.

Now that she is no longer with PhET, is there someone else that you think might want to move this forward? Or close the issue? Or...?

**Comment by pixelzoom** [comment]
@ariel-phet This was an idea that @ycarpenterphet had. Her most recent status on the issue was (https://github.com/phetsims/balancing-chemical-equations/issues/59#issuecomment-49087820):
> I've done some digging into possible reactions, but haven't found any that are reasonable at this time.

Now that she is no longer with PhET, is there someone else that you think might want to move this forward? Or close the issue? Or...?

**Comment by ariel-phet** [comment]
@amyh-phet please review the comments above and the sim and see what you think.

**Comment by amyh-phet** [comment]
@pixelzoom   I haven't been able to come up with any equations that would be suitable for Level 3 of the game using only elements  or molecules supported by nitroglycerin.   Closing issue.

**Comment by pixelzoom** [comment]
Thanks @amyh-phet.
