### ISSUE TITLE
scoreboard has a blank space above it

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balancing-chemical-equations#89]
The top tab [scoreboard] in the game screen of the sim has a blank space above it on Windows 7 Google Chrome Version 36.0.1985.125 m

![bce](https://cloud.githubusercontent.com/assets/5631059/3694724/3f671bc0-1375-11e4-8dea-6c89f4c14c89.png)

Troubleshooting information (do not edit):
Name: Balancing Chemical Equations
URL: http://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.0.0-dev.15/balancing-chemical-equations_en.html
Version: 1.0.0-dev.15
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36
Language: en-US
Window: 1164x848
Pixel Ratio: 1.100000023841858/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 4096 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true

**Comment by pixelzoom** [comment]
This is a general design issue, being addressed in phetsims/vegas#28. 

Closing.
