### ISSUE TITLE
perfect score audio track always plays full track

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/balancing-chemical-equations#92]
If you receive a perfect score on a level, the 'cheering' audio track plays to completion even if the user clicks Continue and returns to the level selection screen and starts the next level.

It feels a bit odd that the cheering sound continues once you've left the feedback/completion screen, though this is really minor complaint.

**Comment by pixelzoom** [comment]
This is a general issue, it's present in all sims with games, being tracked in phetsims/vegas#34. 

Closing.
