### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-chemical-equations#96]
No one has complained about this yet, so probably not high priority.  But BCE is leaking memory, which will result in it slowing down as it's used (especially on iPad).

This was discovered while investigating https://github.com/phetsims/reactants-products-and-leftovers/issues/18 (RPAL memory leak) and https://github.com/phetsims/scenery/issues/328 (scenery leaking radial gradients).  In addition to leaking radial gradients, BCE appears to be leaking AXON properties and sim-specific nodes.  Screenshot below shows a comparison view of 2 heap snapshots, taken with Chrome Dev Tools on Mac OS.

To instrument this test, I added the following to bce.IntroductionView, then ran the sim with '?screens=1&leakStep=8".

```js
  function IntroductionView( model ) {
     this.model = model;
     ...
  }

  var LEAK_STEP = parseInt( window.phetcommon.getQueryParameter( 'leakStep' ), 10 ) || 0;

  return inherit( ScreenView, IntroductionView, {
    // Cycle through the equations, for memory-leak debugging.
    steps: 0,
    equationIndex: 0,
    step: function( dt ) {
      if ( LEAK_STEP > 0 ) {
        this.steps++;
        if ( this.steps % LEAK_STEP === 0 ) {
          this.model.equation = this.model.choices[this.equationIndex++].equation;
          if ( this.equationIndex >= this.model.choices.length ) {
            this.equationIndex = 0;
          }
        }
      }
    }
  } );
```

And I made the following change in EquationTerm, so that some molecules would be displayed:

> 27   initialCoefficient: 3 // initial value of the coefficient

Here's the heap comparison, taken after the sim was running for a few minutes.

![screenshot_152](https://cloud.githubusercontent.com/assets/3046552/5463042/9de58032-8536-11e4-9145-bfaa57445a17.png)

**Comment by pixelzoom** [comment]
@ariel-phet Do you want this investigated for "Summer 2015 redeploy"?

**Comment by ariel-phet** [comment]
Yes, when we go to redeploy the sim it seems worth fixing this issue.

**Comment by pixelzoom** [comment]
No plans to work on this until we revisit this sim. Unassigning until then.

**Comment by pixelzoom** [comment]
There are lots of Property constructor args that are linked to in the constructor. And there are zero `dispose` functions implemented in this sim, to clean up those Property links.

**Comment by pixelzoom** [comment]
I've inspected a lot of the code, documented where dispose functions are not needed, and added TODO items where dispose functions are needed.  I still need to inspect the following source files:

BoxesNode
BoxNode
EqualityOperatorNode
EquationNode
RightArrowNode
TermNode

**Comment by pixelzoom** [comment]
All code has been inspected, and each type now has either: (1) a comment documenting why dispose is not needed, or (2) a TODO item indicating where a memory leak needs to be plugged.

**Comment by pixelzoom** [comment]
The 3 places where dispose calls are missing are:

- [ ] BalanceScaleNode
- [ ] BarNode
- [ ] TermNode

**Comment by pixelzoom** [comment]
Implemented `dispose` in all locations that I identified. On to memory profiling...

**Comment by pixelzoom** [comment]
Repeated the heap comparison described in https://github.com/phetsims/balancing-chemical-equations/issues/96#issue-52175407, new results are shown below.  This looks good, closing.

![screenshot_603](https://cloud.githubusercontent.com/assets/3046552/9744484/562c7704-5629-11e5-8857-875431d04a20.png)
