### ISSUE TITLE
User reported bug: game does not progress through levels in Ubuntu Linux

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balancing-chemical-equations#97]
Test device:   Asus eee

Operating System: forgot

Browser: not sure

Problem description:  When playing balancing equations game, I can make an entry, but the check button does nothing and there is no way to move to the second of the 5 problems in the level.  Help!  My sudent needs to complete this for class. When I click Check, nothing at all happens.  The operating system is Ubuntu.

Steps to reproduce: Play game of balancing equations.

Severity: Everytime I try.

Screenshots:

Troubleshooting information (do not edit):
Name: Balancing Chemical Equations
URL: http://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations_en.html
Version: 1.0.0
Features missing: csstransforms3d, touch
User Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.56 Safari/536.5
Language: en-US
Window: 1024x488
Pixel Ratio: 1/1
WebGL: disabled

**Comment by pixelzoom** [comment]
The browser is reported as "not sure". If we're going to investigate a Linux issue, we definitely need to know the browser - it may be a browser that PhET doesn't support, in which case our recommendation would be to use Chrome or Firefox.

**Comment by oliver-phet** [comment]
User was asked for a screenshot and browser version 3 weeks ago. No reply received yet.

**Comment by pixelzoom** [comment]
The browser is Chrome 19, which is very old. Please tell the user to upgrade their browser to Chrome 39.

**Comment by oliver-phet** [comment]
User was notified on Jan 9. Closing.
