### ISSUE TITLE
User reported bug: equation typo

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balancing-chemical-equations#98]
Problem description: This is a simple typo which causes a logic issue, as can be seen in the screenshot, the answer to the equation is unbalanced because of the number of hydrogen, on the left side of the equation there is 6 and on the right, only 5 (According to the equation, the picture is correct)

Steps to reproduce: No special steps, simply go through the level 3 game until this problem is encountered. 

Severity: Annoyance/Potential cause for confusion

Screenshots:
![image](https://cloud.githubusercontent.com/assets/5090275/5622203/cd979272-94fc-11e4-9ef2-3bd64ae83883.png)

**Comment by pixelzoom** [comment]
This is not a bug. There are 6 hydrogens (not 5) in C<sub>2</sub>H<sub>5</sub>OH.  One hydrogen is bonded to the oxygen, as can be seen in the molecule structure.

**Comment by pixelzoom** [comment]
@oliver-phet Assigning this back to you to communicate with the user who reported this.

**Comment by oliver-phet** [comment]
Email to user sent.
